### ISSUE TITLE
Android: Error inflating class android.support.design.widget.CoordinatorLayout

### ISSUE THREAD

**Issue by ghost** [arielhernandezmusa/capacitor-biometric-auth#9]
I get the above error when I add this plugin to my project and try to run on an Android device and the app immediately crashes.

Very new to capacitor so I can't add much more than that - sorry!

**Comment by iwantwin** [comment]
Had the same problem on my own project, and solved it by changing the bridage_layout_main.xml for androidx support. Created a pull request for my my solution, hope it get's merged to fix this issue for you as well.

**Comment by larsvankleef** [comment]
Would be nice if this pull request got merged I’m try this plugin out but bummed into this error.
